core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('account/', include('account.urls')),
    # path('payment/', include('payment.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/pages/models.py
from django.db import models
from django.shortcuts import reverse


class Categories(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    image = models.ImageField(upload_to='image/categories/', verbose_name='Картинка категории')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['pk']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Products(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    price = models.IntegerField(default=0, verbose_name='Стоимость')
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание на детальную страницу')
    quantity = models.IntegerField(default=0, verbose_name='Количество')
    slug = models.SlugField(max_length=255, verbose_name='ссылка до продукта')

    def __str__(self):
        return self.title

    def get_first_image(self):
        photo = self.product_image.all().first()
        if photo is not None:
            return photo.image.url
        else:
            return 'https://kartinkof.club/uploads/posts/2022-06/1655949284_11-kartinkof-club-p-kartinki-s-nadpisyu-net-ya-s-gorla-12.jpg'

    def get_list_image(self):
        try:
            photo = self.product_image.all()
            return photo
        except:
            return '-'

    def get_absolute_url(self):
        return reverse('detail_path', kwargs={'slug_path': self.slug})

    class Meta:
        ordering = ['pk']
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class ProductGallery(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='product_image')
    image = models.ImageField(upload_to=f'image/product/', blank=True, null=True)


class Worker(models.Model):
    CHOICES_POSITION = [
        ('с', 'Стажер'),
        ('к', 'Кондитер'),
        ('п', 'Пекарь'),
        ('гп', 'Главный пекарь')
    ]
    full_name = models.CharField(max_length=255, verbose_name='ФИО работника')
    years_experience = models.IntegerField(default=0, verbose_name='Годы опыта')
    image = models.ImageField(upload_to='image/team/', verbose_name='Фото работника')
    position = models.CharField(max_length=2, choices=CHOICES_POSITION, default='c', verbose_name='Должность')
    facebook = models.CharField(max_length=200, verbose_name='Ссылка на facebook')
    twitter_x = models.CharField(max_length=200, verbose_name='Ссылка на twitter')
    instagram = models.CharField(max_length=200, verbose_name='Ссылка на instagram')

    def __str__(self):
        return self.full_name

    class Meta:
        ordering = ['pk']
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'

core/pages/templates/pages/detail.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}


{% block content %}
{% include 'pages_component/_header.html' %}

<div class="container bg-light">
    <div class="row">
        <div class="col-5 p-3">
            <div id="carouselExample" class="carousel slide">
                <div class="carousel-inner">
                    {% for photo in product.get_list_image.all %}
                    {% if forloop.counter == 1 %}
                    <div class="carousel-item active">
                        <img src="{{ photo.image.url }}" class="d-block w-100" alt="...">
                    </div>
                    {% else %}
                    <div class="carousel-item">
                        <img src="{{ photo.image.url }}" class="d-block w-100" alt="...">
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                <button class="carousel-control-prev bg-dark" style="width: 50px" type="button"
                        data-bs-target="#carouselExample"
                        data-bs-slide="prev">
                    <i class="bi bi-arrow-left fs-3"></i>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next bg-dark" style="width: 50px" type="button"
                        data-bs-target="#carouselExample"
                        data-bs-slide="next">
                    <i class="bi bi-arrow-right fs-3"></i>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <div class="col-6 p-3">
            <div class="text-center">
                <h3>{{ product.title }}</h3>
            </div>
            <p class="fs-5">
                {{ product.description }}
            </p>
            <div class="d-flex justify-content-around">
                <h5>Количество: <span style="color: #EAA636;">{{ product.quantity }}</span></h5>
                <h5>Стоимость: <span style="color: #EAA636;">{{ product.price }} сум</span></h5>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/pages/templates/pages/index.html
{% extends 'base.html' %}
{% load pages_simple_tag %}

{% block title %}
{{ title }}
{% endblock title %}

{% block content %}
<!-- Carousel Start -->
{% include 'components/_carousel.html' %}
<!-- Carousel End -->

<!-- Facts Start -->
{% include 'components/_facts.html' %}
<!-- Facts End -->


<!-- About Start -->
{% include 'components/_about.html' %}
<!-- About End -->


<!-- Product Start -->
<div class="container-xxl bg-light my-6 py-6 pt-0">
    <div class="container">
        <div class="bg-primary text-light rounded-bottom p-5 my-6 mt-0 wow fadeInUp" data-wow-delay="0.1s">
            <div class="row g-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="display-4 text-light mb-0">Лучшая Пекарня В Вашем Городе</h1>
                </div>
                <div class="col-lg-6 text-lg-end">
                    <div class="d-inline-flex align-items-center text-start">
                        <i class="fa fa-phone-alt fa-4x flex-shrink-0"></i>
                        <div class="ms-4">
                            <p class="fs-5 fw-bold mb-0">Позвоните нам</p>
                            <p class="fs-1 fw-bold mb-0">+998 99 999 99 99</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
            <p class="text-primary text-uppercase mb-2">// Barker Categories</p>
            <h1 class="display-6 mb-4">Ознакомьтесь с нашими категориями</h1>
        </div>
        <div class="row g-4">
            {% get_categories as categories %}
            {% for category in categories %}
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.{{ forloop.counter }}s">
                <div class="product-item d-flex flex-column bg-white rounded overflow-hidden h-100">
                    <div class="text-center p-4">
                        <h3 class="mb-3">{{ category.name }}</h3>
                    </div>
                    <div class="position-relative mt-auto">
                        <img class="img-fluid" src="{{ category.image.url }}" alt="">
                        <div class="product-overlay">
                            <a class="btn btn-lg-square btn-outline-light rounded-circle"
                               href="{% url 'show_category_path' category.name %}">
                                <i class="fa fa-eye text-primary"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Product End -->


<!-- Service Start -->
{% include 'components/_service.html' %}
<!-- Service End -->
{% endblock content %}

core/pages/templates/pages/list_product.html
{% extends 'base.html' %}
{% load pages_simple_tag %}


{% block title %}
{{ title }}
{% endblock title %}

{% block content %}
{% include 'pages_component/_header.html' %}

<div class="container-xxl bg-light my-6 py-6 pt-0" style="margin: 12rem 0;">
    <div class="container">
        <div class="bg-primary text-light rounded-bottom p-5 my-6 mt-0 wow fadeInUp" data-wow-delay="0.1s">
            <div class="row g-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="display-4 text-light mb-0">Лучшая Пекарня В Вашем Городе</h1>
                </div>
                <div class="col-lg-6 text-lg-end">
                    <div class="d-inline-flex align-items-center text-start">
                        <i class="fa fa-phone-alt fa-4x flex-shrink-0"></i>
                        <div class="ms-4">
                            <p class="fs-5 fw-bold mb-0">Позвоните нам</p>
                            <p class="fs-1 fw-bold mb-0">+998 99 999 99 99</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
            <p class="text-primary text-uppercase mb-2">// Barker Категории</p>
            {% get_categories as categories %}
            <div class="d-flex justify-content-around mb-5">
                <a href="{% url 'product_list_path' %}">Все категории</a>
                {% for category in categories %}
                <a href="{% url 'show_category_path' category.name %}">{{ category }}</a>
                {% endfor %}
            </div>

            <p class="text-primary text-uppercase mb-2">// Barker Продукты</p>
        </div>
        <div class="row g-4">
            {% for product in products %}
            <div class="col-lg-5 col-md-6 wow fadeInUp mx-auto" data-wow-delay="0.{{ forloop.counter }}s">
                <div class="product-item d-flex flex-column bg-white rounded overflow-hidden h-100">
                    <div class="text-center p-4">
                        <div class="d-inline-block border border-primary rounded-pill px-3 mb-3">
                            {{ product.price }}
                        </div>
                        <h3 class="mb-3">{{ product.title }}</h3>
                        <span>{{ product.description }}</span>
                    </div>
                    <div class="position-relative mt-auto">
                        <img class="img-fluid p-3" src="{{ product.get_first_image }}" alt="">
                        <div class="product-overlay">
                            <a class="btn btn-lg-square btn-outline-light rounded-circle"
                               href="{{ product.get_absolute_url }}">
                                <i class="fa fa-eye text-primary"></i>
                            </a>
                            <a class="btn btn-lg-square btn-outline-light rounded-circle ms-2"
                               href="{{ product.get_absolute_url }}">
                                <i class="bi bi-cart-plus-fill text-primary"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>


        {% if products %}
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex justify-content-between">
                {% for p in page_obj.paginator.page_range %}
                {% if p == page_obj.number %}
                <a class="custom-page-link-active" href="?page={{ p }}">
                    {{ p }}
                </a>
                {% else %}
                <a class="custom-page-link" href="?page={{ p }}">
                    {{ p }}
                </a>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <a class="custom-page-link" href="?page={{ page_obj.next_page_number }}"
                   aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
                {% endif %}
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

core/pages/templates/pages/team.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock title %}

{% block content %}

{% include 'pages_component/_header.html' %}

<div class="container-xxl py-3">
    <div class="container">
        <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
            <p class="text-primary text-uppercase mb-2">// Наша команда</p>
            <h1 class="display-6 mb-4">Мы Очень Профессионально Относимся к Своим Навыкам</h1>
        </div>
        <div class="row g-4">
            {% for worker in worker_experienced %}
            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.{{ forloop.counter }}s">
                <div class="team-item text-center rounded overflow-hidden">
                    <img class="img-fluid" src="{{ worker.image.url }}" alt="">
                    <div class="team-text">
                        <div class="team-title">
                            <h5>{{ worker.full_name }}</h5>
                            <span>Стаж: {{ worker.years_experience }}</span>
                            <span>Должность: {{ worker.get_position_display }}</span>
                        </div>
                        <div class="team-social">
                            <a class="btn btn-square btn-light rounded-circle" href="{{ worker.facebook }}">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="btn btn-square btn-light rounded-circle" href="{{ worker.twitter_x }}">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="btn btn-square btn-light rounded-circle" href="{{ worker.instagram }}">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>


        <div class="text-center mx-auto mb-5 mt-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
            <p class="text-primary text-uppercase mb-2">// Наша команда Стажеров</p>
            <h6 class="display-6 mb-4">Мы Хотим Стать Профессионалами Данного Дела</h6>
        </div>
        <div class="row g-4">
            {% for worker_i in worker_intern %}
            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.{{ forloop.counter }}s">
                <div class="team-item text-center rounded overflow-hidden">
                    <img class="img-fluid" src="{{ worker_i.image.url }}" style="width: 300px;" alt="">
                    <div class="team-text">
                        <div class="team-title">
                            <h5>{{ worker_i.full_name }}</h5>
                            <span>Должность: {{ worker_i.get_position_display }}</span>
                        </div>
                        <div class="team-social">
                            <a class="btn btn-square btn-light rounded-circle" href="{{ worker_i.facebook }}">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="btn btn-square btn-light rounded-circle" href="{{ worker_i.twitter_x }}">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="btn btn-square btn-light rounded-circle" href="{{ worker_i.instagram }}">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}